# Generated by Django 5.1.5 on 2025-01-18 04:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotonwners',
            name='ownerID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
