# Generated by Django 5.1.5 on 2025-01-25 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0002_vehicle_plotonwners_owner_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reservation',
        ),
        migrations.AddField(
            model_name='review',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='partnerapp.plotonwners'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash')], max_length=20),
        ),
    ]
