# Generated by Django 5.1.5 on 2025-01-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0003_plotonwners_owner_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotonwners',
            name='owner_email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
