# Generated by Django 5.1.5 on 2025-01-25 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0003_remove_review_reservation_review_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='partnerapp.parkingreservation'),
        ),
    ]
