# Generated by Django 5.1.5 on 2025-02-01 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0005_alter_review_rating'),
        ('payapp', '0002_alter_customer__id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='reservation_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.CreateModel(
            name='ParkingReservationPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reservation_status', models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='reserved', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('razorpay', 'Razorpay'), ('cash', 'Cash')], max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('order_id', models.CharField(blank=True, help_text='Razorpay order_id or any external gateway order ID', max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, help_text='Razorpay payment_id or any external gateway payment ID', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='partnerapp.parkingplots')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_reservations', to='payapp.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='ParkingReservation',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
