# Generated by Django 5.1.5 on 2025-02-19 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0006_remove_payment_reservation_id_remove_payment_user_and_more'),
        ('payapp', '0002_alter_customer__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingreservationpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payapp.customer'),
        ),
    ]
