# Generated by Django 5.1.5 on 2025-01-18 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0006_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='parking_station/')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerapp.plotonwners')),
            ],
            options={
                'db_table': 'Parking_Station_Images',
            },
        ),
    ]
