# Generated by Django 5.1.5 on 2025-01-18 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0007_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='partnerapp.plotonwners'),
        ),
    ]
