# Generated by Django 5.1.5 on 2025-02-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0007_alter_parkingreservationpayment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotonwners',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator')], db_index=True, default='operator', max_length=10),
        ),
    ]
