# Generated by Django 5.1.5 on 2025-01-20 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0008_alter_images_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hourly_rate', models.FloatField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerapp.plotonwners')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerapp.vehicle')),
            ],
            options={
                'db_table': 'ParkingCharge',
            },
        ),
    ]
