# Generated by Django 5.1.5 on 2025-02-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0008_alter_plotonwners_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotonwners',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='plotonwners',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
