# Generated by Django 5.1.5 on 2025-01-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0009_parkingcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotonwners',
            name='owner_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
