# Generated by Django 5.1.5 on 2025-02-24 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0009_alter_plotonwners_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotonwners',
            name='ownerID',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
