# Generated by Django 5.1.5 on 2025-01-20 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0010_plotonwners_owner_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingcharge',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='partnerapp.plotonwners'),
        ),
    ]
