# Generated by Django 5.1.5 on 2025-01-20 09:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0011_alter_parkingcharge_owner_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingPlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('plot_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partnerapp.plotonwners')),
            ],
        ),
    ]
