# Generated by Django 5.1.5 on 2025-01-20 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partnerapp', '0012_parkingplots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingplots',
            name='owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='partnerapp.plotonwners'),
        ),
    ]
